import { IntentInterface } from 'src/types/intent';

export const generalIntents: IntentInterface[] = [
  {
    name: 'belongs',
    triggers: [' de ', ' da ', ' com ', ' do ', ' sobre ', ' referente a '],
    answers: [],
  },
  {
    name: 'cancel',
    triggers: [
      ' cancela',
      ' cancelar',
      ' para',
      ' cala a boca',
      ' chega',
      ' já deu',
      ' basta',
      ' pare',
    ],
    answers: ['Okay', 'Entendido', 'Copiado', 'Positivo QPA'],
  },
  {
    name: 'negative',
    triggers: [' não', 'negativo', 'necas', 'nada', 'nenhum', 'nunca', 'nem'],
    answers: [],
  },
  {
    name: 'positive',
    triggers: [
      ' sim',
      'positivo',
      'claro',
      'pode',
      'consegue',
      'aham',
      'certeza',
      'também',
    ],
    answers: [],
  },
  {
    name: 'good',
    triggers: [
      ' bom',
      'positivo',
      ' bem ',
      ' bem.',
      'legal',
      'gostoso',
      'lindo',
      'certeza',
      'ótimo',
      'feliz',
    ],
    answers: [],
  },
  {
    name: 'bad',
    triggers: [
      ' mal.',
      ' mal ',
      'péssimo',
      'horrível',
      'cocô',
      'doente',
      'enjoado',
      'ruim',
      'triste',
      'lamentável',
      'lastima',
      'podre',
      'machucado',
      'ferido',
      'lesionado',
      'morrendo',
      'deprê',
      'depre',
    ],
    answers: [],
  },
];
